title: Yanblog
lang: en
description: a blog

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: false

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
